spring.profiles.active: local
---
spring:
  application:
    name: demo

management:
  endpoint.health:
    show-details: ALWAYS


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
    tryItOutEnabled: true

server:
  forward-headers-strategy: framework
  shutdown: graceful
